---
title: "Untitled"
author: "Lluis Ramon"
date: "10 de mayo de 2014"
output: html_document
---

Ja tenim planificades les pròximes reunions. Una de Machine learning on l'Aleix portarà la veu cantant i una de Shiny on serà el Roc qui ens ensenyarà les bondats i particularitats d'aquest package. Les dues ja estan anunciades al [Meetup de Rugbcn][]. Si encara no esteu apuntats, afegiu-vos, que ja superem els 100 R-users.

[Meetup de Rugbcn]: http://www.meetup.com/RugBcn-Barcelona-R-users-group/

## Machine learning

**Dia: dimecres 21 maig 2014 a les 18:30**
**Lloc: itnig (the hacker accelerator) àlaba 61, 5-2, Barcelona**

Aquesta sessió serà una visió general del camp del Machine Learning. L'Aleix parlarà sobre el principal tipus de tècniques, quines són les aplicacions típiques i com implementar-ho amb R. També s'aprofitarà la sessió per presentar el ["Grup d'Estudi de Machine Learning de Barcelona"][], GEMLeB.

Per apuntar-vos, informació addicional o comentaris aneu al [meetup de l'event][].

["Grup d'Estudi de Machine Learning de Barcelona"]: http://www.meetup.com/Grup-destudi-de-machine-learning-de-Barcelona/

[meetup de l'event]: http://www.meetup.com/RugBcn-Barcelona-R-users-group/events/179271102/

## Introducció a Shiny

**Dia: dimecres 25 juny 2014 18:30**
**Lloc: itnig (the hacker accelerator) àlaba 61, 5-2, Barcelona**

Shiny és un package d'R que permet fer aplicacions interactives de forma relativament fàcil. Pots utilitzar aquestes aplicacions en local o si es disposa d'un servidor tenir-les a la web. Aquestes aplicacions permeten des de gràfics interactius, taules, mapes o el que la teva imaginació i les dades et permetin, donant tota la potència de l'R al teu navegador. Però el millor és que mireu els exemples a continuació http://shiny.rstudio.com/gallery/

Per apuntar-vos, informació addicional o comentaris aneu al [meetup de la introducció a Shiny][].

[meetup de la introducció a Shiny]: http://www.meetup.com/RugBcn-Barcelona-R-users-group/events/181342862/
